[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jani Ronkainen", email = "ronkainen@hotmail.fi" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
backend = "backend:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
