[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jani Ronkainen", email = "ronkainen@hotmail.fi" }
]
requires-python = ">=3.11"
dependencies = [
    "django>=5.2.17",
    "django-ninja>=1.7.1",
]

[project.scripts]
backend = "backend:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"

[tool.uv.workspace]
members = [
    "backend",
]
